function Q = process_image(im,dictionary)

Q = probability_search_km_tree(im, ...
    dictionary.tree, ...
    dictionary.dictprob, ...
    dictionary.options.branching_factor, ...
    dictionary.options.normalization);